quarkus:
  datasource:
    db-kind: postgresql
    username: magnolia
    password: password
    jdbc:
      url: jdbc:postgresql://127.0.0.1:5432/postit
      max-size: 16
  flyway:
    db-kind: postgresql
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/postit
    username: magnolia
    password: password
  native:
    resources:
      includes: publicKey.pem
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: http://localhost:8080
mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: http://localhost:8080
smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
